name: Build and run tests

on:
  push:
    branches: [ main, prod, beta, staging, develop ]
  pull_request:
    branches: [ main, prod, beta, staging, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 10.16.3
        cache: 'npm'
    - run: npm i
    # - run: npm test

  deploy_develop:
    if: contains( github.ref, 'develop')
    runs-on: ubuntu-latest
    needs: build
    environment: develop
    env:
        PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
        HOSTNAME : ${{ secrets.HOSTNAME }}
        USER_NAME : ${{ secrets.USER_NAME }}
    steps:
      - run: echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
      - run: ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} uptime
      - run: |
          ssh -i private_key ${USER_NAME}@${HOSTNAME} '
          . ~/.nvm/nvm.sh &&
          cd freeflow-api &&
          git pull origin develop &&
          npm ci &&
          npm run build &&
          pm2 delete freeflow-api-develop &&
          pm2 start dist/main.js --name "freeflow-api-develop"
          '
